# pyright: reportAttributeAccessIssue=false

"""initial schema

Revision ID: 11944d2ce893
Revises: 
Create Date: 2026-04-29 15:31:34.773486
"""

from typing import Any, Sequence, Union

from alembic import op
import sqlalchemy as sa

from al_medlit.core.types import JSONType

create_table: Any = getattr(op, "create_table")
drop_table: Any = getattr(op, "drop_table")
batch_alter_table: Any = getattr(op, "batch_alter_table")


revision: str = '11944d2ce893'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    create_table('projects',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('annotation_schema', JSONType(), nullable=False),
    sa.Column('settings', JSONType(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_name'), ['name'], unique=True)

    create_table('documents',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('metadata', JSONType(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_project_id'), ['project_id'], unique=False)

    create_table('error_patterns',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.String(length=80), nullable=False),
    sa.Column('error_type', sa.String(length=120), nullable=False),
    sa.Column('label_type', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('example_count', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('detected_from', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('example_ids', JSONType(), nullable=False),
    sa.Column('metadata', JSONType(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with batch_alter_table('error_patterns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_error_patterns_error_type'), ['error_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_error_patterns_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_error_patterns_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_error_patterns_task_type'), ['task_type'], unique=False)

    create_table('guideline_versions',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('version_label', sa.String(length=80), nullable=False),
    sa.Column('markdown', sa.Text(), nullable=False),
    sa.Column('author_id', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with batch_alter_table('guideline_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guideline_versions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guideline_versions_project_id'), ['project_id'], unique=False)

    create_table('annotations',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('annotation_type', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('start_offset', sa.Integer(), nullable=True),
    sa.Column('end_offset', sa.Integer(), nullable=True),
    sa.Column('text_span', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('annotator_id', sa.String(length=120), nullable=True),
    sa.Column('model_checkpoint_id', sa.String(length=255), nullable=True),
    sa.Column('guideline_version_id', sa.Integer(), nullable=True),
    sa.Column('evidence', JSONType(), nullable=False),
    sa.Column('attributes', JSONType(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with batch_alter_table('annotations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_annotations_annotation_type'), ['annotation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_annotations_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_annotations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_annotations_label'), ['label'], unique=False)
        batch_op.create_index(batch_op.f('ix_annotations_project_id'), ['project_id'], unique=False)

    create_table('guideline_atoms',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('guideline_version_id', sa.Integer(), nullable=True),
    sa.Column('error_pattern_id', sa.Integer(), nullable=True),
    sa.Column('task_type', sa.String(length=80), nullable=False),
    sa.Column('error_type', sa.String(length=120), nullable=True),
    sa.Column('rule_text', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('positive_examples', JSONType(), nullable=False),
    sa.Column('negative_examples', JSONType(), nullable=False),
    sa.Column('applies_to', JSONType(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('approved_by', sa.String(length=120), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['error_pattern_id'], ['error_patterns.id'], ),
    sa.ForeignKeyConstraint(['guideline_version_id'], ['guideline_versions.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with batch_alter_table('guideline_atoms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guideline_atoms_error_pattern_id'), ['error_pattern_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guideline_atoms_guideline_version_id'), ['guideline_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guideline_atoms_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guideline_atoms_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guideline_atoms_task_type'), ['task_type'], unique=False)

    create_table('model_predictions',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('model_version', sa.String(length=255), nullable=True),
    sa.Column('task_type', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('start_offset', sa.Integer(), nullable=True),
    sa.Column('end_offset', sa.Integer(), nullable=True),
    sa.Column('text_span', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('evidence', JSONType(), nullable=False),
    sa.Column('raw_output', JSONType(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with batch_alter_table('model_predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_predictions_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_predictions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_predictions_model_name'), ['model_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_predictions_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_predictions_task_type'), ['task_type'], unique=False)

    create_table('annotation_corrections',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('original_annotation_id', sa.Integer(), nullable=True),
    sa.Column('corrected_annotation_id', sa.Integer(), nullable=True),
    sa.Column('correction_source', sa.String(length=50), nullable=False),
    sa.Column('correction_note', sa.Text(), nullable=True),
    sa.Column('error_type', sa.String(length=120), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('metadata', JSONType(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['corrected_annotation_id'], ['annotations.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['original_annotation_id'], ['annotations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with batch_alter_table('annotation_corrections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_annotation_corrections_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_annotation_corrections_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_annotation_corrections_project_id'), ['project_id'], unique=False)

    create_table('micro_question_templates',
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('guideline_atom_id', sa.Integer(), nullable=True),
    sa.Column('error_type', sa.String(length=120), nullable=False),
    sa.Column('target_annotation_type', sa.String(length=80), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('answer_options', JSONType(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['guideline_atom_id'], ['guideline_atoms.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with batch_alter_table('micro_question_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_micro_question_templates_error_type'), ['error_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_micro_question_templates_guideline_atom_id'), ['guideline_atom_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_micro_question_templates_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_micro_question_templates_project_id'), ['project_id'], unique=False)

    create_table('training_actions',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('error_pattern_id', sa.Integer(), nullable=True),
    sa.Column('guideline_atom_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(length=120), nullable=False),
    sa.Column('target_model', sa.String(length=255), nullable=False),
    sa.Column('example_ids', JSONType(), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['error_pattern_id'], ['error_patterns.id'], ),
    sa.ForeignKeyConstraint(['guideline_atom_id'], ['guideline_atoms.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with batch_alter_table('training_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_actions_action_type'), ['action_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_actions_error_pattern_id'), ['error_pattern_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_actions_guideline_atom_id'), ['guideline_atom_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_actions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_actions_project_id'), ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with batch_alter_table('training_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_actions_project_id'))
        batch_op.drop_index(batch_op.f('ix_training_actions_id'))
        batch_op.drop_index(batch_op.f('ix_training_actions_guideline_atom_id'))
        batch_op.drop_index(batch_op.f('ix_training_actions_error_pattern_id'))
        batch_op.drop_index(batch_op.f('ix_training_actions_action_type'))

    drop_table('training_actions')
    with batch_alter_table('micro_question_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_micro_question_templates_project_id'))
        batch_op.drop_index(batch_op.f('ix_micro_question_templates_id'))
        batch_op.drop_index(batch_op.f('ix_micro_question_templates_guideline_atom_id'))
        batch_op.drop_index(batch_op.f('ix_micro_question_templates_error_type'))

    drop_table('micro_question_templates')
    with batch_alter_table('annotation_corrections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_annotation_corrections_project_id'))
        batch_op.drop_index(batch_op.f('ix_annotation_corrections_id'))
        batch_op.drop_index(batch_op.f('ix_annotation_corrections_document_id'))

    drop_table('annotation_corrections')
    with batch_alter_table('model_predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_predictions_task_type'))
        batch_op.drop_index(batch_op.f('ix_model_predictions_project_id'))
        batch_op.drop_index(batch_op.f('ix_model_predictions_model_name'))
        batch_op.drop_index(batch_op.f('ix_model_predictions_id'))
        batch_op.drop_index(batch_op.f('ix_model_predictions_document_id'))

    drop_table('model_predictions')
    with batch_alter_table('guideline_atoms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guideline_atoms_task_type'))
        batch_op.drop_index(batch_op.f('ix_guideline_atoms_project_id'))
        batch_op.drop_index(batch_op.f('ix_guideline_atoms_id'))
        batch_op.drop_index(batch_op.f('ix_guideline_atoms_guideline_version_id'))
        batch_op.drop_index(batch_op.f('ix_guideline_atoms_error_pattern_id'))

    drop_table('guideline_atoms')
    with batch_alter_table('annotations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_annotations_project_id'))
        batch_op.drop_index(batch_op.f('ix_annotations_label'))
        batch_op.drop_index(batch_op.f('ix_annotations_id'))
        batch_op.drop_index(batch_op.f('ix_annotations_document_id'))
        batch_op.drop_index(batch_op.f('ix_annotations_annotation_type'))

    drop_table('annotations')
    with batch_alter_table('guideline_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guideline_versions_project_id'))
        batch_op.drop_index(batch_op.f('ix_guideline_versions_id'))

    drop_table('guideline_versions')
    with batch_alter_table('error_patterns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_error_patterns_task_type'))
        batch_op.drop_index(batch_op.f('ix_error_patterns_project_id'))
        batch_op.drop_index(batch_op.f('ix_error_patterns_id'))
        batch_op.drop_index(batch_op.f('ix_error_patterns_error_type'))

    drop_table('error_patterns')
    with batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_project_id'))
        batch_op.drop_index(batch_op.f('ix_documents_id'))
        batch_op.drop_index(batch_op.f('ix_documents_external_id'))

    drop_table('documents')
    with batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_name'))
        batch_op.drop_index(batch_op.f('ix_projects_id'))

    drop_table('projects')
    # ### end Alembic commands ###
