"""add evidence blocks training and inference

Revision ID: 7a2e4c9b1d60
Revises: 3f8d1c7a9b24
Create Date: 2026-07-15 17:39:08.912952
"""

from collections.abc import Sequence

from alembic import op
import al_medlit.core.types
import sqlalchemy as sa


revision: str = '7a2e4c9b1d60'
down_revision: str | None = '3f8d1c7a9b24'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compute_profiles',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('backend', sa.String(length=40), nullable=False),
    sa.Column('config', al_medlit.core.types.JSONType(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_compute_profiles_project_name')
    )
    with op.batch_alter_table('compute_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compute_profiles_backend'), ['backend'], unique=False)
        batch_op.create_index(batch_op.f('ix_compute_profiles_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_compute_profiles_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_compute_profiles_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_compute_profiles_status'), ['status'], unique=False)

    op.create_table('lineage_artifacts',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('artifact_type', sa.String(length=80), nullable=False),
    sa.Column('schema_version', sa.String(length=40), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('manifest', al_medlit.core.types.JSONType(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    with op.batch_alter_table('lineage_artifacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lineage_artifacts_artifact_type'), ['artifact_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_lineage_artifacts_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_lineage_artifacts_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lineage_artifacts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lineage_artifacts_project_id'), ['project_id'], unique=False)

    op.create_table('corpus_snapshots',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('artifact_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('split_strategy', sa.String(length=80), nullable=False),
    sa.Column('split_seed', sa.Integer(), nullable=False),
    sa.Column('document_count', sa.Integer(), nullable=False),
    sa.Column('metadata', al_medlit.core.types.JSONType(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['lineage_artifacts.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('corpus_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_corpus_snapshots_artifact_id'), ['artifact_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_corpus_snapshots_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_corpus_snapshots_project_id'), ['project_id'], unique=False)

    op.create_table('document_structure_versions',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('segmenter_name', sa.String(length=80), nullable=False),
    sa.Column('segmenter_version', sa.String(length=40), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('text_length', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('source_metadata', al_medlit.core.types.JSONType(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint('text_length >= 0', name='ck_document_structure_versions_text_length'),
    sa.CheckConstraint('version >= 1', name='ck_document_structure_versions_version'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'version', name='uq_document_structure_versions_document_version')
    )
    with op.batch_alter_table('document_structure_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_structure_versions_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_structure_versions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_structure_versions_source_hash'), ['source_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_structure_versions_status'), ['status'], unique=False)

    op.create_table('evidence_targets',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active_version_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['project_tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'key', name='uq_evidence_targets_project_key')
    )
    with op.batch_alter_table('evidence_targets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_targets_active_version_id'), ['active_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_targets_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_targets_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_targets_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_targets_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_targets_task_id'), ['task_id'], unique=False)

    op.create_table('lineage_edges',
    sa.Column('upstream_artifact_id', sa.Integer(), nullable=False),
    sa.Column('downstream_artifact_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.String(length=80), nullable=False),
    sa.Column('metadata', al_medlit.core.types.JSONType(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('upstream_artifact_id <> downstream_artifact_id', name='ck_lineage_edge_not_self_referential'),
    sa.ForeignKeyConstraint(['downstream_artifact_id'], ['lineage_artifacts.id'], ),
    sa.ForeignKeyConstraint(['upstream_artifact_id'], ['lineage_artifacts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('upstream_artifact_id', 'downstream_artifact_id', 'relationship_type', name='uq_lineage_edge_artifacts_relationship')
    )
    with op.batch_alter_table('lineage_edges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lineage_edges_downstream_artifact_id'), ['downstream_artifact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lineage_edges_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lineage_edges_upstream_artifact_id'), ['upstream_artifact_id'], unique=False)

    op.create_table('annotation_sets',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('artifact_id', sa.Integer(), nullable=False),
    sa.Column('corpus_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('target_version_ids', al_medlit.core.types.JSONType(), nullable=False),
    sa.Column('guideline_version_ids', al_medlit.core.types.JSONType(), nullable=False),
    sa.Column('block_count', sa.Integer(), nullable=False),
    sa.Column('reviewed_region_count', sa.Integer(), nullable=False),
    sa.Column('metadata', al_medlit.core.types.JSONType(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['lineage_artifacts.id'], ),
    sa.ForeignKeyConstraint(['corpus_snapshot_id'], ['corpus_snapshots.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('annotation_sets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_annotation_sets_artifact_id'), ['artifact_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_annotation_sets_corpus_snapshot_id'), ['corpus_snapshot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_annotation_sets_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_annotation_sets_project_id'), ['project_id'], unique=False)

    op.create_table('corpus_snapshot_documents',
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('structure_version_id', sa.Integer(), nullable=False),
    sa.Column('split', sa.String(length=20), nullable=False),
    sa.Column('group_key', sa.String(length=255), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('metadata', al_medlit.core.types.JSONType(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['corpus_snapshots.id'], ),
    sa.ForeignKeyConstraint(['structure_version_id'], ['document_structure_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id', 'document_id', name='uq_corpus_snapshot_document')
    )
    with op.batch_alter_table('corpus_snapshot_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_corpus_snapshot_documents_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_corpus_snapshot_documents_group_key'), ['group_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_corpus_snapshot_documents_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_corpus_snapshot_documents_snapshot_id'), ['snapshot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_corpus_snapshot_documents_split'), ['split'], unique=False)
        batch_op.create_index(batch_op.f('ix_corpus_snapshot_documents_structure_version_id'), ['structure_version_id'], unique=False)

    op.create_table('document_sections',
    sa.Column('structure_version_id', sa.Integer(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('path', al_medlit.core.types.JSONType(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('start_offset', sa.Integer(), nullable=False),
    sa.Column('end_offset', sa.Integer(), nullable=False),
    sa.Column('locator', al_medlit.core.types.JSONType(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint('ordinal >= 0', name='ck_document_sections_ordinal'),
    sa.CheckConstraint('start_offset >= 0 AND end_offset >= start_offset', name='ck_document_sections_offsets'),
    sa.ForeignKeyConstraint(['structure_version_id'], ['document_structure_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('structure_version_id', 'ordinal', name='uq_document_sections_structure_ordinal')
    )
    with op.batch_alter_table('document_sections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_sections_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_sections_structure_version_id'), ['structure_version_id'], unique=False)

    op.create_table('evidence_target_versions',
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('guidance', sa.Text(), nullable=True),
    sa.Column('inclusion_guidance', sa.Text(), nullable=True),
    sa.Column('exclusion_guidance', sa.Text(), nullable=True),
    sa.Column('metadata', al_medlit.core.types.JSONType(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['evidence_targets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_id', 'version_number', name='uq_evidence_target_versions_target_number')
    )
    with op.batch_alter_table('evidence_target_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_target_versions_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_target_versions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_target_versions_target_id'), ['target_id'], unique=False)

    # The target and its active immutable version form an intentional cycle.
    # Add this edge only after both tables exist so the migration works on
    # PostgreSQL as well as SQLite batch migrations.
    with op.batch_alter_table('evidence_targets', schema=None) as batch_op:
        batch_op.create_foreign_key(
            'fk_evidence_targets_active_version_id',
            'evidence_target_versions',
            ['active_version_id'],
            ['id'],
            ondelete='SET NULL',
        )

    op.create_table('annotation_set_review_regions',
    sa.Column('annotation_set_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('structure_version_id', sa.Integer(), nullable=False),
    sa.Column('target_version_id', sa.Integer(), nullable=False),
    sa.Column('start_sentence_ordinal', sa.Integer(), nullable=False),
    sa.Column('end_sentence_ordinal', sa.Integer(), nullable=False),
    sa.Column('metadata', al_medlit.core.types.JSONType(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['annotation_set_id'], ['annotation_sets.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['structure_version_id'], ['document_structure_versions.id'], ),
    sa.ForeignKeyConstraint(['target_version_id'], ['evidence_target_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('annotation_set_review_regions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_annotation_set_review_regions_annotation_set_id'), ['annotation_set_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_annotation_set_review_regions_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_annotation_set_review_regions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_annotation_set_review_regions_structure_version_id'), ['structure_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_annotation_set_review_regions_target_version_id'), ['target_version_id'], unique=False)

    op.create_table('document_paragraphs',
    sa.Column('structure_version_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('section_ordinal', sa.Integer(), nullable=False),
    sa.Column('start_offset', sa.Integer(), nullable=False),
    sa.Column('end_offset', sa.Integer(), nullable=False),
    sa.Column('locator', al_medlit.core.types.JSONType(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint('ordinal >= 0', name='ck_document_paragraphs_ordinal'),
    sa.CheckConstraint('section_ordinal >= 0', name='ck_document_paragraphs_section_ordinal'),
    sa.CheckConstraint('start_offset >= 0 AND end_offset >= start_offset', name='ck_document_paragraphs_offsets'),
    sa.ForeignKeyConstraint(['section_id'], ['document_sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['structure_version_id'], ['document_structure_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section_id', 'section_ordinal', name='uq_document_paragraphs_section_ordinal'),
    sa.UniqueConstraint('structure_version_id', 'ordinal', name='uq_document_paragraphs_structure_ordinal')
    )
    with op.batch_alter_table('document_paragraphs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_paragraphs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_paragraphs_section_id'), ['section_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_paragraphs_structure_version_id'), ['structure_version_id'], unique=False)

    op.create_table('evidence_block_revisions',
    sa.Column('annotation_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('structure_version_id', sa.Integer(), nullable=False),
    sa.Column('target_version_id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('operation', sa.String(length=50), nullable=False),
    sa.Column('before', al_medlit.core.types.JSONType(), nullable=True),
    sa.Column('after', al_medlit.core.types.JSONType(), nullable=True),
    sa.Column('command_group_key', sa.String(length=64), nullable=False),
    sa.Column('is_undone', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['annotation_id'], ['annotations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['structure_version_id'], ['document_structure_versions.id'], ),
    sa.ForeignKeyConstraint(['target_version_id'], ['evidence_target_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence_block_revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_block_revisions_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_block_revisions_annotation_id'), ['annotation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_block_revisions_command_group_key'), ['command_group_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_block_revisions_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_block_revisions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_block_revisions_is_undone'), ['is_undone'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_block_revisions_operation'), ['operation'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_block_revisions_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_block_revisions_structure_version_id'), ['structure_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_block_revisions_target_version_id'), ['target_version_id'], unique=False)

    op.create_table('export_artifacts',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('artifact_id', sa.Integer(), nullable=False),
    sa.Column('corpus_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('annotation_set_id', sa.Integer(), nullable=True),
    sa.Column('format_key', sa.String(length=100), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('metadata', al_medlit.core.types.JSONType(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['annotation_set_id'], ['annotation_sets.id'], ),
    sa.ForeignKeyConstraint(['artifact_id'], ['lineage_artifacts.id'], ),
    sa.ForeignKeyConstraint(['corpus_snapshot_id'], ['corpus_snapshots.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('export_artifacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_export_artifacts_annotation_set_id'), ['annotation_set_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_export_artifacts_artifact_id'), ['artifact_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_export_artifacts_corpus_snapshot_id'), ['corpus_snapshot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_export_artifacts_format_key'), ['format_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_export_artifacts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_export_artifacts_project_id'), ['project_id'], unique=False)

    op.create_table('document_sentences',
    sa.Column('structure_version_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('paragraph_id', sa.Integer(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('paragraph_ordinal', sa.Integer(), nullable=False),
    sa.Column('start_offset', sa.Integer(), nullable=False),
    sa.Column('end_offset', sa.Integer(), nullable=False),
    sa.Column('text_hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint('ordinal >= 0', name='ck_document_sentences_ordinal'),
    sa.CheckConstraint('paragraph_ordinal >= 0', name='ck_document_sentences_paragraph_ordinal'),
    sa.CheckConstraint('start_offset >= 0 AND end_offset > start_offset', name='ck_document_sentences_offsets'),
    sa.ForeignKeyConstraint(['paragraph_id'], ['document_paragraphs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['document_sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['structure_version_id'], ['document_structure_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paragraph_id', 'paragraph_ordinal', name='uq_document_sentences_paragraph_ordinal'),
    sa.UniqueConstraint('structure_version_id', 'ordinal', name='uq_document_sentences_structure_ordinal')
    )
    with op.batch_alter_table('document_sentences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_sentences_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_sentences_paragraph_id'), ['paragraph_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_sentences_section_id'), ['section_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_sentences_structure_version_id'), ['structure_version_id'], unique=False)

    op.create_table('training_experiments',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('annotation_set_id', sa.Integer(), nullable=False),
    sa.Column('dataset_export_artifact_id', sa.Integer(), nullable=True),
    sa.Column('compute_profile_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('model_type', sa.String(length=100), nullable=False),
    sa.Column('mode', sa.String(length=30), nullable=False),
    sa.Column('target_version_ids', al_medlit.core.types.JSONType(), nullable=False),
    sa.Column('config', al_medlit.core.types.JSONType(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['annotation_set_id'], ['annotation_sets.id'], ),
    sa.ForeignKeyConstraint(['compute_profile_id'], ['compute_profiles.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dataset_export_artifact_id'], ['export_artifacts.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'idempotency_key', name='uq_training_experiments_project_idempotency')
    )
    with op.batch_alter_table('training_experiments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_experiments_annotation_set_id'), ['annotation_set_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_experiments_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_experiments_dataset_export_artifact_id'), ['dataset_export_artifact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_experiments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_experiments_mode'), ['mode'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_experiments_model_type'), ['model_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_experiments_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_experiments_status'), ['status'], unique=False)

    op.create_table('annotation_set_items',
    sa.Column('annotation_set_id', sa.Integer(), nullable=False),
    sa.Column('source_annotation_id', sa.Integer(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('structure_version_id', sa.Integer(), nullable=False),
    sa.Column('target_version_id', sa.Integer(), nullable=False),
    sa.Column('guideline_version_id', sa.Integer(), nullable=True),
    sa.Column('start_sentence_id', sa.Integer(), nullable=False),
    sa.Column('end_sentence_id', sa.Integer(), nullable=False),
    sa.Column('start_sentence_ordinal', sa.Integer(), nullable=False),
    sa.Column('end_sentence_ordinal', sa.Integer(), nullable=False),
    sa.Column('start_char', sa.Integer(), nullable=False),
    sa.Column('end_char', sa.Integer(), nullable=False),
    sa.Column('block_text', sa.Text(), nullable=False),
    sa.Column('section_paths', al_medlit.core.types.JSONType(), nullable=False),
    sa.Column('labels', al_medlit.core.types.JSONType(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('metadata', al_medlit.core.types.JSONType(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['annotation_set_id'], ['annotation_sets.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['end_sentence_id'], ['document_sentences.id'], ),
    sa.ForeignKeyConstraint(['guideline_version_id'], ['guideline_versions.id'], ),
    sa.ForeignKeyConstraint(['source_annotation_id'], ['annotations.id'], ),
    sa.ForeignKeyConstraint(['start_sentence_id'], ['document_sentences.id'], ),
    sa.ForeignKeyConstraint(['structure_version_id'], ['document_structure_versions.id'], ),
    sa.ForeignKeyConstraint(['target_version_id'], ['evidence_target_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('annotation_set_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_annotation_set_items_annotation_set_id'), ['annotation_set_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_annotation_set_items_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_annotation_set_items_guideline_version_id'), ['guideline_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_annotation_set_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_annotation_set_items_source_annotation_id'), ['source_annotation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_annotation_set_items_structure_version_id'), ['structure_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_annotation_set_items_target_version_id'), ['target_version_id'], unique=False)

    op.create_table('evidence_block_annotations',
    sa.Column('annotation_id', sa.Integer(), nullable=False),
    sa.Column('structure_version_id', sa.Integer(), nullable=False),
    sa.Column('target_version_id', sa.Integer(), nullable=False),
    sa.Column('start_sentence_id', sa.Integer(), nullable=False),
    sa.Column('end_sentence_id', sa.Integer(), nullable=False),
    sa.Column('start_sentence_ordinal', sa.Integer(), nullable=False),
    sa.Column('end_sentence_ordinal', sa.Integer(), nullable=False),
    sa.Column('labels', al_medlit.core.types.JSONType(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('boundary_policy', sa.String(length=50), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('last_command_group_key', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['annotation_id'], ['annotations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['end_sentence_id'], ['document_sentences.id'], ),
    sa.ForeignKeyConstraint(['start_sentence_id'], ['document_sentences.id'], ),
    sa.ForeignKeyConstraint(['structure_version_id'], ['document_structure_versions.id'], ),
    sa.ForeignKeyConstraint(['target_version_id'], ['evidence_target_versions.id'], ),
    sa.PrimaryKeyConstraint('annotation_id')
    )
    with op.batch_alter_table('evidence_block_annotations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_block_annotations_end_sentence_id'), ['end_sentence_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_block_annotations_last_command_group_key'), ['last_command_group_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_block_annotations_start_sentence_id'), ['start_sentence_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_block_annotations_structure_version_id'), ['structure_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_block_annotations_target_version_id'), ['target_version_id'], unique=False)

    op.create_table('evidence_review_coverage',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('structure_version_id', sa.Integer(), nullable=False),
    sa.Column('target_version_id', sa.Integer(), nullable=False),
    sa.Column('guideline_version_id', sa.Integer(), nullable=True),
    sa.Column('reviewer_user_id', sa.Integer(), nullable=False),
    sa.Column('start_sentence_id', sa.Integer(), nullable=False),
    sa.Column('end_sentence_id', sa.Integer(), nullable=False),
    sa.Column('start_sentence_ordinal', sa.Integer(), nullable=False),
    sa.Column('end_sentence_ordinal', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['end_sentence_id'], ['document_sentences.id'], ),
    sa.ForeignKeyConstraint(['guideline_version_id'], ['guideline_versions.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['reviewer_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['start_sentence_id'], ['document_sentences.id'], ),
    sa.ForeignKeyConstraint(['structure_version_id'], ['document_structure_versions.id'], ),
    sa.ForeignKeyConstraint(['target_version_id'], ['evidence_target_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence_review_coverage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_review_coverage_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_review_coverage_guideline_version_id'), ['guideline_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_review_coverage_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_review_coverage_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_review_coverage_reviewer_user_id'), ['reviewer_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_review_coverage_structure_version_id'), ['structure_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_review_coverage_target_version_id'), ['target_version_id'], unique=False)

    op.create_table('evidence_review_events',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('structure_version_id', sa.Integer(), nullable=False),
    sa.Column('target_version_id', sa.Integer(), nullable=False),
    sa.Column('guideline_version_id', sa.Integer(), nullable=True),
    sa.Column('actor_user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('start_sentence_id', sa.Integer(), nullable=False),
    sa.Column('end_sentence_id', sa.Integer(), nullable=False),
    sa.Column('start_sentence_ordinal', sa.Integer(), nullable=False),
    sa.Column('end_sentence_ordinal', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('metadata', al_medlit.core.types.JSONType(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['end_sentence_id'], ['document_sentences.id'], ),
    sa.ForeignKeyConstraint(['guideline_version_id'], ['guideline_versions.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['start_sentence_id'], ['document_sentences.id'], ),
    sa.ForeignKeyConstraint(['structure_version_id'], ['document_structure_versions.id'], ),
    sa.ForeignKeyConstraint(['target_version_id'], ['evidence_target_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence_review_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_review_events_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_review_events_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_review_events_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_review_events_guideline_version_id'), ['guideline_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_review_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_review_events_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_review_events_structure_version_id'), ['structure_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_review_events_target_version_id'), ['target_version_id'], unique=False)

    op.create_table('training_jobs',
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('target_version_id', sa.Integer(), nullable=True),
    sa.Column('compute_profile_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('idempotency_key', sa.String(length=160), nullable=False),
    sa.Column('external_job_id', sa.String(length=120), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('bundle_artifact_id', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('metrics', al_medlit.core.types.JSONType(), nullable=False),
    sa.Column('runtime_metadata', al_medlit.core.types.JSONType(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bundle_artifact_id'], ['lineage_artifacts.id'], ),
    sa.ForeignKeyConstraint(['compute_profile_id'], ['compute_profiles.id'], ),
    sa.ForeignKeyConstraint(['experiment_id'], ['training_experiments.id'], ),
    sa.ForeignKeyConstraint(['target_version_id'], ['evidence_target_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_training_jobs_idempotency_key')
    )
    with op.batch_alter_table('training_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_jobs_bundle_artifact_id'), ['bundle_artifact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_jobs_compute_profile_id'), ['compute_profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_jobs_experiment_id'), ['experiment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_jobs_external_job_id'), ['external_job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_jobs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_jobs_target_version_id'), ['target_version_id'], unique=False)

    op.create_table('model_checkpoints',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('training_job_id', sa.Integer(), nullable=False),
    sa.Column('artifact_id', sa.Integer(), nullable=False),
    sa.Column('model_type', sa.String(length=100), nullable=False),
    sa.Column('training_mode', sa.String(length=30), nullable=False),
    sa.Column('trained_target_version_ids', al_medlit.core.types.JSONType(), nullable=False),
    sa.Column('base_model_id', sa.String(length=255), nullable=True),
    sa.Column('base_model_revision', sa.String(length=255), nullable=True),
    sa.Column('max_context_tokens', sa.Integer(), nullable=False),
    sa.Column('manifest', al_medlit.core.types.JSONType(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['lineage_artifacts.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['training_job_id'], ['training_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_checkpoints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_checkpoints_artifact_id'), ['artifact_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_model_checkpoints_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_checkpoints_model_type'), ['model_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_checkpoints_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_checkpoints_training_job_id'), ['training_job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_checkpoints_training_mode'), ['training_mode'], unique=False)

    op.create_table('inference_runs',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('corpus_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('checkpoint_id', sa.Integer(), nullable=False),
    sa.Column('compute_profile_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('target_version_ids', al_medlit.core.types.JSONType(), nullable=False),
    sa.Column('window_config', al_medlit.core.types.JSONType(), nullable=False),
    sa.Column('decoder_config', al_medlit.core.types.JSONType(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=False),
    sa.Column('external_job_id', sa.String(length=120), nullable=True),
    sa.Column('diagnostics_artifact_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('metrics', al_medlit.core.types.JSONType(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['checkpoint_id'], ['model_checkpoints.id'], ),
    sa.ForeignKeyConstraint(['compute_profile_id'], ['compute_profiles.id'], ),
    sa.ForeignKeyConstraint(['corpus_snapshot_id'], ['corpus_snapshots.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['diagnostics_artifact_id'], ['lineage_artifacts.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'idempotency_key', name='uq_inference_runs_project_idempotency')
    )
    with op.batch_alter_table('inference_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inference_runs_checkpoint_id'), ['checkpoint_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inference_runs_compute_profile_id'), ['compute_profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inference_runs_corpus_snapshot_id'), ['corpus_snapshot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inference_runs_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inference_runs_diagnostics_artifact_id'), ['diagnostics_artifact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inference_runs_external_job_id'), ['external_job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inference_runs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inference_runs_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inference_runs_status'), ['status'], unique=False)

    op.create_table('evidence_candidate_predictions',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('checkpoint_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('structure_version_id', sa.Integer(), nullable=False),
    sa.Column('target_version_id', sa.Integer(), nullable=False),
    sa.Column('start_sentence_id', sa.Integer(), nullable=False),
    sa.Column('end_sentence_id', sa.Integer(), nullable=False),
    sa.Column('start_sentence_ordinal', sa.Integer(), nullable=False),
    sa.Column('end_sentence_ordinal', sa.Integer(), nullable=False),
    sa.Column('start_char', sa.Integer(), nullable=False),
    sa.Column('end_char', sa.Integer(), nullable=False),
    sa.Column('block_confidence', sa.Float(), nullable=False),
    sa.Column('boundary_confidence', al_medlit.core.types.JSONType(), nullable=False),
    sa.Column('uncertainty', sa.Float(), nullable=False),
    sa.Column('decoder_version', sa.String(length=80), nullable=False),
    sa.Column('source_window_ids', al_medlit.core.types.JSONType(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('diagnostics_artifact_id', sa.Integer(), nullable=True),
    sa.Column('metadata', al_medlit.core.types.JSONType(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['checkpoint_id'], ['model_checkpoints.id'], ),
    sa.ForeignKeyConstraint(['diagnostics_artifact_id'], ['lineage_artifacts.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['end_sentence_id'], ['document_sentences.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['inference_runs.id'], ),
    sa.ForeignKeyConstraint(['start_sentence_id'], ['document_sentences.id'], ),
    sa.ForeignKeyConstraint(['structure_version_id'], ['document_structure_versions.id'], ),
    sa.ForeignKeyConstraint(['target_version_id'], ['evidence_target_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'document_id', 'target_version_id', 'start_sentence_ordinal', 'end_sentence_ordinal', name='uq_evidence_candidate_run_scope_boundary')
    )
    with op.batch_alter_table('evidence_candidate_predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_candidate_predictions_checkpoint_id'), ['checkpoint_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_candidate_predictions_diagnostics_artifact_id'), ['diagnostics_artifact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_candidate_predictions_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_candidate_predictions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_candidate_predictions_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_candidate_predictions_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_candidate_predictions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_candidate_predictions_structure_version_id'), ['structure_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_candidate_predictions_target_version_id'), ['target_version_id'], unique=False)

    op.create_table('inference_windows',
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('structure_version_id', sa.Integer(), nullable=False),
    sa.Column('target_version_id', sa.Integer(), nullable=False),
    sa.Column('stable_key', sa.String(length=80), nullable=False),
    sa.Column('start_sentence_ordinal', sa.Integer(), nullable=False),
    sa.Column('end_sentence_ordinal', sa.Integer(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('sentence_contribution_counts', al_medlit.core.types.JSONType(), nullable=False),
    sa.Column('diagnostics_artifact_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['diagnostics_artifact_id'], ['lineage_artifacts.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['inference_runs.id'], ),
    sa.ForeignKeyConstraint(['structure_version_id'], ['document_structure_versions.id'], ),
    sa.ForeignKeyConstraint(['target_version_id'], ['evidence_target_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'stable_key', name='uq_inference_windows_run_key')
    )
    with op.batch_alter_table('inference_windows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inference_windows_diagnostics_artifact_id'), ['diagnostics_artifact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inference_windows_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inference_windows_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inference_windows_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inference_windows_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_inference_windows_structure_version_id'), ['structure_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inference_windows_target_version_id'), ['target_version_id'], unique=False)

    op.create_table('evidence_prediction_reviews',
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('resulting_annotation_id', sa.Integer(), nullable=True),
    sa.Column('selected_boundaries', al_medlit.core.types.JSONType(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('metadata', al_medlit.core.types.JSONType(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['evidence_candidate_predictions.id'], ),
    sa.ForeignKeyConstraint(['resulting_annotation_id'], ['annotations.id'], ),
    sa.ForeignKeyConstraint(['reviewer_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prediction_id', 'revision', name='uq_evidence_prediction_review_revision')
    )
    with op.batch_alter_table('evidence_prediction_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_prediction_reviews_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_prediction_reviews_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_prediction_reviews_prediction_id'), ['prediction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_prediction_reviews_resulting_annotation_id'), ['resulting_annotation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_prediction_reviews_reviewer_user_id'), ['reviewer_user_id'], unique=False)

    with op.batch_alter_table('annotation_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assignment_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_annotation_submissions_assignment_id'), ['assignment_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_annotation_submissions_assignment_id_task_assignments',
            'task_assignments',
            ['assignment_id'],
            ['id'],
        )

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_structure_version_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_documents_active_structure_version_id'), ['active_structure_version_id'], unique=False)
        batch_op.create_foreign_key('fk_documents_active_structure_version_id', 'document_structure_versions', ['active_structure_version_id'], ['id'], ondelete='SET NULL', use_alter=True)

    with op.batch_alter_table('task_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_version_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('structure_version_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('guideline_version_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('assignment_scope_key', sa.String(length=160), nullable=True))

    # Existing assignment rows retain their document-scoped behavior. New
    # evidence assignments use target-specific portable scope keys.
    op.execute(
        sa.text(
            "UPDATE task_assignments "
            "SET assignment_scope_key = 'document' "
            "WHERE assignment_scope_key IS NULL"
        )
    )

    with op.batch_alter_table('task_assignments', schema=None) as batch_op:
        batch_op.alter_column(
            'assignment_scope_key',
            existing_type=sa.String(length=160),
            nullable=False,
        )
        batch_op.drop_constraint(batch_op.f('uq_task_assignments_task_document_assignee'), type_='unique')
        batch_op.create_index(batch_op.f('ix_task_assignments_assignment_scope_key'), ['assignment_scope_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_assignments_guideline_version_id'), ['guideline_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_assignments_structure_version_id'), ['structure_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_assignments_target_version_id'), ['target_version_id'], unique=False)
        batch_op.create_unique_constraint('uq_task_assignments_task_document_assignee_scope', ['task_id', 'document_id', 'assignee_user_id', 'assignment_scope_key'])
        batch_op.create_foreign_key('fk_task_assignments_structure_version_id', 'document_structure_versions', ['structure_version_id'], ['id'])
        batch_op.create_foreign_key('fk_task_assignments_guideline_version_id', 'guideline_versions', ['guideline_version_id'], ['id'])
        batch_op.create_foreign_key('fk_task_assignments_target_version_id', 'evidence_target_versions', ['target_version_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_assignments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_task_assignments_target_version_id', type_='foreignkey')
        batch_op.drop_constraint('fk_task_assignments_guideline_version_id', type_='foreignkey')
        batch_op.drop_constraint('fk_task_assignments_structure_version_id', type_='foreignkey')
        batch_op.drop_constraint('uq_task_assignments_task_document_assignee_scope', type_='unique')
        batch_op.drop_index(batch_op.f('ix_task_assignments_target_version_id'))
        batch_op.drop_index(batch_op.f('ix_task_assignments_structure_version_id'))
        batch_op.drop_index(batch_op.f('ix_task_assignments_guideline_version_id'))
        batch_op.drop_index(batch_op.f('ix_task_assignments_assignment_scope_key'))
        batch_op.create_unique_constraint(batch_op.f('uq_task_assignments_task_document_assignee'), ['task_id', 'document_id', 'assignee_user_id'])
        batch_op.drop_column('assignment_scope_key')
        batch_op.drop_column('guideline_version_id')
        batch_op.drop_column('structure_version_id')
        batch_op.drop_column('target_version_id')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint('fk_documents_active_structure_version_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_documents_active_structure_version_id'))
        batch_op.drop_column('active_structure_version_id')

    with op.batch_alter_table('annotation_submissions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_annotation_submissions_assignment_id_task_assignments', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_annotation_submissions_assignment_id'))
        batch_op.drop_column('assignment_id')

    with op.batch_alter_table('evidence_prediction_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_prediction_reviews_reviewer_user_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_prediction_reviews_resulting_annotation_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_prediction_reviews_prediction_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_prediction_reviews_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_prediction_reviews_action'))

    op.drop_table('evidence_prediction_reviews')
    with op.batch_alter_table('inference_windows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inference_windows_target_version_id'))
        batch_op.drop_index(batch_op.f('ix_inference_windows_structure_version_id'))
        batch_op.drop_index(batch_op.f('ix_inference_windows_status'))
        batch_op.drop_index(batch_op.f('ix_inference_windows_run_id'))
        batch_op.drop_index(batch_op.f('ix_inference_windows_id'))
        batch_op.drop_index(batch_op.f('ix_inference_windows_document_id'))
        batch_op.drop_index(batch_op.f('ix_inference_windows_diagnostics_artifact_id'))

    op.drop_table('inference_windows')
    with op.batch_alter_table('evidence_candidate_predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_candidate_predictions_target_version_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_candidate_predictions_structure_version_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_candidate_predictions_status'))
        batch_op.drop_index(batch_op.f('ix_evidence_candidate_predictions_run_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_candidate_predictions_project_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_candidate_predictions_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_candidate_predictions_document_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_candidate_predictions_diagnostics_artifact_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_candidate_predictions_checkpoint_id'))

    op.drop_table('evidence_candidate_predictions')
    with op.batch_alter_table('inference_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inference_runs_status'))
        batch_op.drop_index(batch_op.f('ix_inference_runs_project_id'))
        batch_op.drop_index(batch_op.f('ix_inference_runs_id'))
        batch_op.drop_index(batch_op.f('ix_inference_runs_external_job_id'))
        batch_op.drop_index(batch_op.f('ix_inference_runs_diagnostics_artifact_id'))
        batch_op.drop_index(batch_op.f('ix_inference_runs_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_inference_runs_corpus_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_inference_runs_compute_profile_id'))
        batch_op.drop_index(batch_op.f('ix_inference_runs_checkpoint_id'))

    op.drop_table('inference_runs')
    with op.batch_alter_table('model_checkpoints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_checkpoints_training_mode'))
        batch_op.drop_index(batch_op.f('ix_model_checkpoints_training_job_id'))
        batch_op.drop_index(batch_op.f('ix_model_checkpoints_project_id'))
        batch_op.drop_index(batch_op.f('ix_model_checkpoints_model_type'))
        batch_op.drop_index(batch_op.f('ix_model_checkpoints_id'))
        batch_op.drop_index(batch_op.f('ix_model_checkpoints_artifact_id'))

    op.drop_table('model_checkpoints')
    with op.batch_alter_table('training_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_jobs_target_version_id'))
        batch_op.drop_index(batch_op.f('ix_training_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_training_jobs_id'))
        batch_op.drop_index(batch_op.f('ix_training_jobs_external_job_id'))
        batch_op.drop_index(batch_op.f('ix_training_jobs_experiment_id'))
        batch_op.drop_index(batch_op.f('ix_training_jobs_compute_profile_id'))
        batch_op.drop_index(batch_op.f('ix_training_jobs_bundle_artifact_id'))

    op.drop_table('training_jobs')
    with op.batch_alter_table('evidence_review_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_review_events_target_version_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_review_events_structure_version_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_review_events_project_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_review_events_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_review_events_guideline_version_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_review_events_document_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_review_events_actor_user_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_review_events_action'))

    op.drop_table('evidence_review_events')
    with op.batch_alter_table('evidence_review_coverage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_review_coverage_target_version_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_review_coverage_structure_version_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_review_coverage_reviewer_user_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_review_coverage_project_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_review_coverage_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_review_coverage_guideline_version_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_review_coverage_document_id'))

    op.drop_table('evidence_review_coverage')
    with op.batch_alter_table('evidence_block_annotations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_block_annotations_target_version_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_block_annotations_structure_version_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_block_annotations_start_sentence_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_block_annotations_last_command_group_key'))
        batch_op.drop_index(batch_op.f('ix_evidence_block_annotations_end_sentence_id'))

    op.drop_table('evidence_block_annotations')
    with op.batch_alter_table('annotation_set_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_annotation_set_items_target_version_id'))
        batch_op.drop_index(batch_op.f('ix_annotation_set_items_structure_version_id'))
        batch_op.drop_index(batch_op.f('ix_annotation_set_items_source_annotation_id'))
        batch_op.drop_index(batch_op.f('ix_annotation_set_items_id'))
        batch_op.drop_index(batch_op.f('ix_annotation_set_items_guideline_version_id'))
        batch_op.drop_index(batch_op.f('ix_annotation_set_items_document_id'))
        batch_op.drop_index(batch_op.f('ix_annotation_set_items_annotation_set_id'))

    op.drop_table('annotation_set_items')
    with op.batch_alter_table('training_experiments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_experiments_status'))
        batch_op.drop_index(batch_op.f('ix_training_experiments_project_id'))
        batch_op.drop_index(batch_op.f('ix_training_experiments_model_type'))
        batch_op.drop_index(batch_op.f('ix_training_experiments_mode'))
        batch_op.drop_index(batch_op.f('ix_training_experiments_id'))
        batch_op.drop_index(batch_op.f('ix_training_experiments_dataset_export_artifact_id'))
        batch_op.drop_index(batch_op.f('ix_training_experiments_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_training_experiments_annotation_set_id'))

    op.drop_table('training_experiments')
    with op.batch_alter_table('document_sentences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_sentences_structure_version_id'))
        batch_op.drop_index(batch_op.f('ix_document_sentences_section_id'))
        batch_op.drop_index(batch_op.f('ix_document_sentences_paragraph_id'))
        batch_op.drop_index(batch_op.f('ix_document_sentences_id'))

    op.drop_table('document_sentences')
    with op.batch_alter_table('export_artifacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_export_artifacts_project_id'))
        batch_op.drop_index(batch_op.f('ix_export_artifacts_id'))
        batch_op.drop_index(batch_op.f('ix_export_artifacts_format_key'))
        batch_op.drop_index(batch_op.f('ix_export_artifacts_corpus_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_export_artifacts_artifact_id'))
        batch_op.drop_index(batch_op.f('ix_export_artifacts_annotation_set_id'))

    op.drop_table('export_artifacts')
    with op.batch_alter_table('evidence_block_revisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_block_revisions_target_version_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_block_revisions_structure_version_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_block_revisions_project_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_block_revisions_operation'))
        batch_op.drop_index(batch_op.f('ix_evidence_block_revisions_is_undone'))
        batch_op.drop_index(batch_op.f('ix_evidence_block_revisions_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_block_revisions_document_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_block_revisions_command_group_key'))
        batch_op.drop_index(batch_op.f('ix_evidence_block_revisions_annotation_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_block_revisions_actor_user_id'))

    op.drop_table('evidence_block_revisions')
    with op.batch_alter_table('document_paragraphs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_paragraphs_structure_version_id'))
        batch_op.drop_index(batch_op.f('ix_document_paragraphs_section_id'))
        batch_op.drop_index(batch_op.f('ix_document_paragraphs_id'))

    op.drop_table('document_paragraphs')
    with op.batch_alter_table('annotation_set_review_regions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_annotation_set_review_regions_target_version_id'))
        batch_op.drop_index(batch_op.f('ix_annotation_set_review_regions_structure_version_id'))
        batch_op.drop_index(batch_op.f('ix_annotation_set_review_regions_id'))
        batch_op.drop_index(batch_op.f('ix_annotation_set_review_regions_document_id'))
        batch_op.drop_index(batch_op.f('ix_annotation_set_review_regions_annotation_set_id'))

    op.drop_table('annotation_set_review_regions')
    with op.batch_alter_table('evidence_target_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_target_versions_target_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_target_versions_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_target_versions_created_by_user_id'))

    op.drop_table('evidence_target_versions')
    with op.batch_alter_table('document_sections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_sections_structure_version_id'))
        batch_op.drop_index(batch_op.f('ix_document_sections_id'))

    op.drop_table('document_sections')
    with op.batch_alter_table('corpus_snapshot_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_corpus_snapshot_documents_structure_version_id'))
        batch_op.drop_index(batch_op.f('ix_corpus_snapshot_documents_split'))
        batch_op.drop_index(batch_op.f('ix_corpus_snapshot_documents_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_corpus_snapshot_documents_id'))
        batch_op.drop_index(batch_op.f('ix_corpus_snapshot_documents_group_key'))
        batch_op.drop_index(batch_op.f('ix_corpus_snapshot_documents_document_id'))

    op.drop_table('corpus_snapshot_documents')
    with op.batch_alter_table('annotation_sets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_annotation_sets_project_id'))
        batch_op.drop_index(batch_op.f('ix_annotation_sets_id'))
        batch_op.drop_index(batch_op.f('ix_annotation_sets_corpus_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_annotation_sets_artifact_id'))

    op.drop_table('annotation_sets')
    with op.batch_alter_table('lineage_edges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lineage_edges_upstream_artifact_id'))
        batch_op.drop_index(batch_op.f('ix_lineage_edges_id'))
        batch_op.drop_index(batch_op.f('ix_lineage_edges_downstream_artifact_id'))

    op.drop_table('lineage_edges')
    with op.batch_alter_table('evidence_targets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_targets_task_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_targets_project_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_targets_is_active'))
        batch_op.drop_index(batch_op.f('ix_evidence_targets_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_targets_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_targets_active_version_id'))

    op.drop_table('evidence_targets')
    with op.batch_alter_table('document_structure_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_structure_versions_status'))
        batch_op.drop_index(batch_op.f('ix_document_structure_versions_source_hash'))
        batch_op.drop_index(batch_op.f('ix_document_structure_versions_id'))
        batch_op.drop_index(batch_op.f('ix_document_structure_versions_document_id'))

    op.drop_table('document_structure_versions')
    with op.batch_alter_table('corpus_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_corpus_snapshots_project_id'))
        batch_op.drop_index(batch_op.f('ix_corpus_snapshots_id'))
        batch_op.drop_index(batch_op.f('ix_corpus_snapshots_artifact_id'))

    op.drop_table('corpus_snapshots')
    with op.batch_alter_table('lineage_artifacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lineage_artifacts_project_id'))
        batch_op.drop_index(batch_op.f('ix_lineage_artifacts_id'))
        batch_op.drop_index(batch_op.f('ix_lineage_artifacts_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_lineage_artifacts_content_hash'))
        batch_op.drop_index(batch_op.f('ix_lineage_artifacts_artifact_type'))

    op.drop_table('lineage_artifacts')
    with op.batch_alter_table('compute_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compute_profiles_status'))
        batch_op.drop_index(batch_op.f('ix_compute_profiles_project_id'))
        batch_op.drop_index(batch_op.f('ix_compute_profiles_id'))
        batch_op.drop_index(batch_op.f('ix_compute_profiles_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_compute_profiles_backend'))

    op.drop_table('compute_profiles')
    # ### end Alembic commands ###
