"""add task-neutral learning workflow

Revision ID: f8c5d3e0b217
Revises: e7b4c2d9a106
Create Date: 2026-07-27 13:44:09.180559
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from al_medlit.core.types import JSONType


revision: str = 'f8c5d3e0b217'
down_revision: Union[str, None] = 'e7b4c2d9a106'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasets',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_datasets_project_name')
    )
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_datasets_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_datasets_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_datasets_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_datasets_source_type'), ['source_type'], unique=False)

    op.create_table('execution_environments',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('environment_class', sa.String(length=80), nullable=False),
    sa.Column('image_digest', sa.String(length=255), nullable=True),
    sa.Column('package_manifest', JSONType(), nullable=False),
    sa.Column('hardware_constraints', JSONType(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('verification_report', JSONType(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_execution_environments_project_name')
    )
    with op.batch_alter_table('execution_environments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_execution_environments_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_environments_environment_class'), ['environment_class'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_environments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_environments_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_environments_status'), ['status'], unique=False)

    op.create_table('registered_models',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('lifecycle_status', sa.String(length=30), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_registered_models_project_name')
    )
    with op.batch_alter_table('registered_models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registered_models_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_registered_models_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_registered_models_lifecycle_status'), ['lifecycle_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_registered_models_project_id'), ['project_id'], unique=False)

    op.create_table('storage_policies',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('backend', sa.String(length=40), nullable=False),
    sa.Column('artifact_prefix', sa.String(length=512), nullable=False),
    sa.Column('retention_class', sa.String(length=40), nullable=False),
    sa.Column('encryption', JSONType(), nullable=False),
    sa.Column('cache_policy', JSONType(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_storage_policies_project_name')
    )
    with op.batch_alter_table('storage_policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_storage_policies_backend'), ['backend'], unique=False)
        batch_op.create_index(batch_op.f('ix_storage_policies_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_storage_policies_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_storage_policies_is_default'), ['is_default'], unique=False)
        batch_op.create_index(batch_op.f('ix_storage_policies_project_id'), ['project_id'], unique=False)

    op.create_table('task_definitions',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'key', name='uq_task_definitions_project_key')
    )
    with op.batch_alter_table('task_definitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_definitions_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_definitions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_definitions_project_id'), ['project_id'], unique=False)

    op.create_table('training_recipes',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'key', name='uq_training_recipes_project_key')
    )
    with op.batch_alter_table('training_recipes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_recipes_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_recipes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_recipes_project_id'), ['project_id'], unique=False)

    op.create_table('guidelines',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('task_definition_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['task_definition_id'], ['task_definitions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'task_definition_id', 'name', name='uq_guidelines_project_task_name')
    )
    with op.batch_alter_table('guidelines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guidelines_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guidelines_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guidelines_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guidelines_task_definition_id'), ['task_definition_id'], unique=False)

    op.create_table('task_versions',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('task_definition_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('task_kind', sa.String(length=60), nullable=False),
    sa.Column('input_schema', JSONType(), nullable=False),
    sa.Column('output_schema', JSONType(), nullable=False),
    sa.Column('label_rules', JSONType(), nullable=False),
    sa.Column('annotation_ui', JSONType(), nullable=False),
    sa.Column('metrics', JSONType(), nullable=False),
    sa.Column('trainer_compatibility', JSONType(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('version_number > 0', name='ck_task_versions_positive_version'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['task_definition_id'], ['task_definitions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_definition_id', 'content_hash', name='uq_task_versions_definition_hash'),
    sa.UniqueConstraint('task_definition_id', 'version_number', name='uq_task_versions_definition_version')
    )
    with op.batch_alter_table('task_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_versions_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_versions_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_versions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_versions_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_versions_task_definition_id'), ['task_definition_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_versions_task_kind'), ['task_kind'], unique=False)

    op.create_table('training_recipe_versions',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('training_recipe_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('trainer_plugin_key', sa.String(length=120), nullable=False),
    sa.Column('trainer_plugin_version', sa.String(length=60), nullable=False),
    sa.Column('compatible_task_kinds', JSONType(), nullable=False),
    sa.Column('environment_class', sa.String(length=80), nullable=False),
    sa.Column('config_schema', JSONType(), nullable=False),
    sa.Column('default_config', JSONType(), nullable=False),
    sa.Column('evaluation_defaults', JSONType(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('version_number > 0', name='ck_training_recipe_versions_positive_version'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['training_recipe_id'], ['training_recipes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('training_recipe_id', 'content_hash', name='uq_training_recipe_versions_recipe_hash'),
    sa.UniqueConstraint('training_recipe_id', 'version_number', name='uq_training_recipe_versions_recipe_version')
    )
    with op.batch_alter_table('training_recipe_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_recipe_versions_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_recipe_versions_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_recipe_versions_environment_class'), ['environment_class'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_recipe_versions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_recipe_versions_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_recipe_versions_trainer_plugin_key'), ['trainer_plugin_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_recipe_versions_training_recipe_id'), ['training_recipe_id'], unique=False)

    op.create_table('dataset_versions',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('source_uri', sa.String(length=1024), nullable=True),
    sa.Column('source_revision', sa.String(length=255), nullable=False),
    sa.Column('source_format', sa.String(length=40), nullable=False),
    sa.Column('data_schema', JSONType(), nullable=False),
    sa.Column('provenance', JSONType(), nullable=False),
    sa.Column('license_info', JSONType(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('artifact_package_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('item_count >= 0', name='ck_dataset_versions_nonnegative_count'),
    sa.CheckConstraint('version_number > 0', name='ck_dataset_versions_positive_version'),
    sa.ForeignKeyConstraint(['artifact_package_id'], ['artifact_packages.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id', 'content_hash', name='uq_dataset_versions_dataset_hash'),
    sa.UniqueConstraint('dataset_id', 'version_number', name='uq_dataset_versions_dataset_version')
    )
    with op.batch_alter_table('dataset_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dataset_versions_artifact_package_id'), ['artifact_package_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dataset_versions_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_dataset_versions_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dataset_versions_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dataset_versions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dataset_versions_project_id'), ['project_id'], unique=False)

    op.create_table('guideline_revisions',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('guideline_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('parent_revision_id', sa.Integer(), nullable=True),
    sa.Column('task_version_id', sa.Integer(), nullable=False),
    sa.Column('markdown', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('diff_summary', JSONType(), nullable=False),
    sa.Column('source_proposal_ids', JSONType(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('version_number > 0', name='ck_guideline_revisions_positive_version'),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['guideline_id'], ['guidelines.id'], ),
    sa.ForeignKeyConstraint(['parent_revision_id'], ['guideline_revisions.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['task_version_id'], ['task_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guideline_id', 'content_hash', name='uq_guideline_revisions_guideline_hash'),
    sa.UniqueConstraint('guideline_id', 'version_number', name='uq_guideline_revisions_guideline_version')
    )
    with op.batch_alter_table('guideline_revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guideline_revisions_approved_by_user_id'), ['approved_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guideline_revisions_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_guideline_revisions_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guideline_revisions_guideline_id'), ['guideline_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guideline_revisions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guideline_revisions_parent_revision_id'), ['parent_revision_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guideline_revisions_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guideline_revisions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_guideline_revisions_task_version_id'), ['task_version_id'], unique=False)

    op.create_table('dataset_items',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('dataset_version_id', sa.Integer(), nullable=False),
    sa.Column('stable_key', sa.String(length=255), nullable=False),
    sa.Column('group_key', sa.String(length=255), nullable=True),
    sa.Column('payload', JSONType(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_versions.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_version_id', 'stable_key', name='uq_dataset_items_version_stable_key')
    )
    with op.batch_alter_table('dataset_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dataset_items_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_dataset_items_dataset_version_id'), ['dataset_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dataset_items_group_key'), ['group_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_dataset_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dataset_items_project_id'), ['project_id'], unique=False)

    op.create_table('guideline_change_proposals',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('guideline_id', sa.Integer(), nullable=False),
    sa.Column('base_revision_id', sa.Integer(), nullable=True),
    sa.Column('feedback_event_ids', JSONType(), nullable=False),
    sa.Column('proposed_change', JSONType(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resulting_revision_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['base_revision_id'], ['guideline_revisions.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['guideline_id'], ['guidelines.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['resulting_revision_id'], ['guideline_revisions.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guideline_change_proposals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guideline_change_proposals_base_revision_id'), ['base_revision_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guideline_change_proposals_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guideline_change_proposals_guideline_id'), ['guideline_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guideline_change_proposals_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guideline_change_proposals_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guideline_change_proposals_resulting_revision_id'), ['resulting_revision_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guideline_change_proposals_reviewed_by_user_id'), ['reviewed_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guideline_change_proposals_status'), ['status'], unique=False)

    op.create_table('label_set_versions',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('dataset_version_id', sa.Integer(), nullable=False),
    sa.Column('task_version_id', sa.Integer(), nullable=False),
    sa.Column('parent_version_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('source_kind', sa.String(length=40), nullable=False),
    sa.Column('composition_policy', sa.String(length=20), nullable=False),
    sa.Column('labels', JSONType(), nullable=False),
    sa.Column('label_count', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('artifact_package_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('label_count >= 0', name='ck_label_set_versions_nonnegative_count'),
    sa.CheckConstraint('version_number > 0', name='ck_label_set_versions_positive_version'),
    sa.ForeignKeyConstraint(['artifact_package_id'], ['artifact_packages.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_versions.id'], ),
    sa.ForeignKeyConstraint(['parent_version_id'], ['label_set_versions.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['task_version_id'], ['task_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_version_id', 'task_version_id', 'name', 'version_number', name='uq_label_set_versions_identity')
    )
    with op.batch_alter_table('label_set_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_label_set_versions_artifact_package_id'), ['artifact_package_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_label_set_versions_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_label_set_versions_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_label_set_versions_dataset_version_id'), ['dataset_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_label_set_versions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_label_set_versions_parent_version_id'), ['parent_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_label_set_versions_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_label_set_versions_source_kind'), ['source_kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_label_set_versions_task_version_id'), ['task_version_id'], unique=False)

    op.create_table('split_maps',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('dataset_version_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('strategy', sa.String(length=60), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('group_key_field', sa.String(length=255), nullable=True),
    sa.Column('assignments', JSONType(), nullable=False),
    sa.Column('protected_splits', JSONType(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_versions.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_version_id', 'name', name='uq_split_maps_dataset_name')
    )
    with op.batch_alter_table('split_maps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_split_maps_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_split_maps_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_split_maps_dataset_version_id'), ['dataset_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_split_maps_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_split_maps_project_id'), ['project_id'], unique=False)

    op.create_table('training_dataset_versions',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('dataset_version_id', sa.Integer(), nullable=False),
    sa.Column('task_version_id', sa.Integer(), nullable=False),
    sa.Column('label_set_version_ids', JSONType(), nullable=False),
    sa.Column('split_map_id', sa.Integer(), nullable=False),
    sa.Column('composition', JSONType(), nullable=False),
    sa.Column('preprocessing', JSONType(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('artifact_package_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artifact_package_id'], ['artifact_packages.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_versions.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['split_map_id'], ['split_maps.id'], ),
    sa.ForeignKeyConstraint(['task_version_id'], ['task_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'content_hash', name='uq_training_dataset_versions_project_hash')
    )
    with op.batch_alter_table('training_dataset_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_dataset_versions_artifact_package_id'), ['artifact_package_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_dataset_versions_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_dataset_versions_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_dataset_versions_dataset_version_id'), ['dataset_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_dataset_versions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_dataset_versions_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_dataset_versions_split_map_id'), ['split_map_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_dataset_versions_task_version_id'), ['task_version_id'], unique=False)

    op.create_table('model_versions',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('registered_model_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('parent_version_id', sa.Integer(), nullable=True),
    sa.Column('task_version_id', sa.Integer(), nullable=False),
    sa.Column('training_dataset_version_id', sa.Integer(), nullable=True),
    sa.Column('legacy_training_experiment_id', sa.Integer(), nullable=True),
    sa.Column('family', sa.String(length=80), nullable=False),
    sa.Column('framework', sa.String(length=80), nullable=False),
    sa.Column('base_model', JSONType(), nullable=False),
    sa.Column('training_method', sa.String(length=60), nullable=False),
    sa.Column('recipe_key', sa.String(length=120), nullable=False),
    sa.Column('recipe_version', sa.String(length=60), nullable=False),
    sa.Column('parameters', JSONType(), nullable=False),
    sa.Column('metrics', JSONType(), nullable=False),
    sa.Column('runtime_digest', sa.String(length=64), nullable=False),
    sa.Column('code_digest', sa.String(length=64), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('checkpoint_package_id', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('version_number > 0', name='ck_model_versions_positive_version'),
    sa.ForeignKeyConstraint(['checkpoint_package_id'], ['artifact_packages.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['legacy_training_experiment_id'], ['training_experiments.id'], ),
    sa.ForeignKeyConstraint(['parent_version_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['registered_model_id'], ['registered_models.id'], ),
    sa.ForeignKeyConstraint(['task_version_id'], ['task_versions.id'], ),
    sa.ForeignKeyConstraint(['training_dataset_version_id'], ['training_dataset_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registered_model_id', 'version_number', name='uq_model_versions_model_version')
    )
    with op.batch_alter_table('model_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_versions_checkpoint_package_id'), ['checkpoint_package_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_versions_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_versions_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_versions_family'), ['family'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_versions_framework'), ['framework'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_versions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_versions_legacy_training_experiment_id'), ['legacy_training_experiment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_versions_parent_version_id'), ['parent_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_versions_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_versions_registered_model_id'), ['registered_model_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_versions_task_version_id'), ['task_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_versions_training_dataset_version_id'), ['training_dataset_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_versions_training_method'), ['training_method'], unique=False)

    op.create_table('learning_cycles',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('parent_cycle_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('goal', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('current_stage', sa.String(length=40), nullable=False),
    sa.Column('task_version_id', sa.Integer(), nullable=False),
    sa.Column('source_dataset_version_id', sa.Integer(), nullable=False),
    sa.Column('baseline_model_version_id', sa.Integer(), nullable=True),
    sa.Column('output_training_dataset_version_id', sa.Integer(), nullable=True),
    sa.Column('output_model_version_id', sa.Integer(), nullable=True),
    sa.Column('metadata', JSONType(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('sequence > 0', name='ck_learning_cycles_positive_sequence'),
    sa.ForeignKeyConstraint(['baseline_model_version_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['output_model_version_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['output_training_dataset_version_id'], ['training_dataset_versions.id'], ),
    sa.ForeignKeyConstraint(['parent_cycle_id'], ['learning_cycles.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['source_dataset_version_id'], ['dataset_versions.id'], ),
    sa.ForeignKeyConstraint(['task_version_id'], ['task_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'sequence', name='uq_learning_cycles_project_sequence')
    )
    with op.batch_alter_table('learning_cycles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_cycles_baseline_model_version_id'), ['baseline_model_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_cycles_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_cycles_current_stage'), ['current_stage'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_cycles_goal'), ['goal'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_cycles_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_cycles_output_model_version_id'), ['output_model_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_cycles_output_training_dataset_version_id'), ['output_training_dataset_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_cycles_parent_cycle_id'), ['parent_cycle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_cycles_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_cycles_source_dataset_version_id'), ['source_dataset_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_cycles_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_cycles_task_version_id'), ['task_version_id'], unique=False)

    op.create_table('training_runs',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('registered_model_id', sa.Integer(), nullable=False),
    sa.Column('task_version_id', sa.Integer(), nullable=False),
    sa.Column('training_dataset_version_id', sa.Integer(), nullable=False),
    sa.Column('recipe_version_id', sa.Integer(), nullable=False),
    sa.Column('parent_model_version_id', sa.Integer(), nullable=True),
    sa.Column('environment_id', sa.Integer(), nullable=False),
    sa.Column('storage_policy_id', sa.Integer(), nullable=False),
    sa.Column('evaluation_plan', JSONType(), nullable=False),
    sa.Column('config', JSONType(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('idempotency_key', sa.String(length=160), nullable=False),
    sa.Column('launch_hash', sa.String(length=64), nullable=False),
    sa.Column('output_model_version_id', sa.Integer(), nullable=True),
    sa.Column('runtime_snapshot', JSONType(), nullable=False),
    sa.Column('storage_snapshot', JSONType(), nullable=False),
    sa.Column('failure_code', sa.String(length=80), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['environment_id'], ['execution_environments.id'], ),
    sa.ForeignKeyConstraint(['output_model_version_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['parent_model_version_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['recipe_version_id'], ['training_recipe_versions.id'], ),
    sa.ForeignKeyConstraint(['registered_model_id'], ['registered_models.id'], ),
    sa.ForeignKeyConstraint(['storage_policy_id'], ['storage_policies.id'], ),
    sa.ForeignKeyConstraint(['task_version_id'], ['task_versions.id'], ),
    sa.ForeignKeyConstraint(['training_dataset_version_id'], ['training_dataset_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'idempotency_key', name='uq_training_runs_project_idempotency')
    )
    with op.batch_alter_table('training_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_runs_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_runs_environment_id'), ['environment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_runs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_runs_launch_hash'), ['launch_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_runs_output_model_version_id'), ['output_model_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_runs_parent_model_version_id'), ['parent_model_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_runs_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_runs_recipe_version_id'), ['recipe_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_runs_registered_model_id'), ['registered_model_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_runs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_runs_storage_policy_id'), ['storage_policy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_runs_task_version_id'), ['task_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_runs_training_dataset_version_id'), ['training_dataset_version_id'], unique=False)

    op.create_table('feedback_runs',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=True),
    sa.Column('dataset_version_id', sa.Integer(), nullable=False),
    sa.Column('task_version_id', sa.Integer(), nullable=False),
    sa.Column('producer_type', sa.String(length=40), nullable=False),
    sa.Column('model_version_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=120), nullable=True),
    sa.Column('external_model_id', sa.String(length=255), nullable=True),
    sa.Column('exact_revision', sa.String(length=255), nullable=True),
    sa.Column('prompt_template_hash', sa.String(length=64), nullable=True),
    sa.Column('configuration', JSONType(), nullable=False),
    sa.Column('data_egress_policy', JSONType(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['cycle_id'], ['learning_cycles.id'], ),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_versions.id'], ),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['task_version_id'], ['task_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedback_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_runs_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_runs_cycle_id'), ['cycle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_runs_dataset_version_id'), ['dataset_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_runs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_runs_model_version_id'), ['model_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_runs_producer_type'), ['producer_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_runs_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_runs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_runs_task_version_id'), ['task_version_id'], unique=False)

    op.create_table('feedback_set_versions',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('feedback_run_id', sa.Integer(), nullable=False),
    sa.Column('dataset_version_id', sa.Integer(), nullable=False),
    sa.Column('task_version_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('output_schema', JSONType(), nullable=False),
    sa.Column('candidate_count', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('artifact_package_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('candidate_count >= 0', name='ck_feedback_sets_nonnegative_count'),
    sa.CheckConstraint('version_number > 0', name='ck_feedback_set_versions_positive_version'),
    sa.ForeignKeyConstraint(['artifact_package_id'], ['artifact_packages.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_versions.id'], ),
    sa.ForeignKeyConstraint(['feedback_run_id'], ['feedback_runs.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['task_version_id'], ['task_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feedback_run_id', 'version_number', name='uq_feedback_set_versions_run_version')
    )
    with op.batch_alter_table('feedback_set_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_set_versions_artifact_package_id'), ['artifact_package_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_set_versions_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_set_versions_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_set_versions_dataset_version_id'), ['dataset_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_set_versions_feedback_run_id'), ['feedback_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_set_versions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_set_versions_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_set_versions_task_version_id'), ['task_version_id'], unique=False)

    op.create_table('feedback_candidates',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('feedback_set_version_id', sa.Integer(), nullable=False),
    sa.Column('dataset_item_id', sa.Integer(), nullable=False),
    sa.Column('candidate_key', sa.String(length=120), nullable=False),
    sa.Column('output', JSONType(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('explanation', JSONType(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_item_id'], ['dataset_items.id'], ),
    sa.ForeignKeyConstraint(['feedback_set_version_id'], ['feedback_set_versions.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feedback_set_version_id', 'dataset_item_id', 'candidate_key', name='uq_feedback_candidates_set_item_key')
    )
    with op.batch_alter_table('feedback_candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_candidates_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_candidates_dataset_item_id'), ['dataset_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_candidates_feedback_set_version_id'), ['feedback_set_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_candidates_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_candidates_project_id'), ['project_id'], unique=False)

    op.create_table('selection_runs',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=True),
    sa.Column('dataset_version_id', sa.Integer(), nullable=False),
    sa.Column('task_version_id', sa.Integer(), nullable=False),
    sa.Column('feedback_set_version_id', sa.Integer(), nullable=True),
    sa.Column('split_map_id', sa.Integer(), nullable=True),
    sa.Column('strategy', sa.String(length=60), nullable=False),
    sa.Column('parameters', JSONType(), nullable=False),
    sa.Column('eligibility_filter', JSONType(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['cycle_id'], ['learning_cycles.id'], ),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_versions.id'], ),
    sa.ForeignKeyConstraint(['feedback_set_version_id'], ['feedback_set_versions.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['split_map_id'], ['split_maps.id'], ),
    sa.ForeignKeyConstraint(['task_version_id'], ['task_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('selection_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_selection_runs_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_selection_runs_cycle_id'), ['cycle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_selection_runs_dataset_version_id'), ['dataset_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_selection_runs_feedback_set_version_id'), ['feedback_set_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_selection_runs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_selection_runs_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_selection_runs_split_map_id'), ['split_map_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_selection_runs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_selection_runs_strategy'), ['strategy'], unique=False)
        batch_op.create_index(batch_op.f('ix_selection_runs_task_version_id'), ['task_version_id'], unique=False)

    op.create_table('selection_set_versions',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('selection_run_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('items', JSONType(), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('item_count >= 0', name='ck_selection_set_versions_nonnegative_count'),
    sa.CheckConstraint('version_number > 0', name='ck_selection_set_versions_positive_version'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['selection_run_id'], ['selection_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('selection_run_id', 'version_number', name='uq_selection_set_versions_run_version')
    )
    with op.batch_alter_table('selection_set_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_selection_set_versions_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_selection_set_versions_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_selection_set_versions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_selection_set_versions_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_selection_set_versions_selection_run_id'), ['selection_run_id'], unique=False)

    op.create_table('annotation_rounds',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('parent_round_id', sa.Integer(), nullable=True),
    sa.Column('cycle_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('dataset_version_id', sa.Integer(), nullable=False),
    sa.Column('task_version_id', sa.Integer(), nullable=False),
    sa.Column('guideline_revision_id', sa.Integer(), nullable=True),
    sa.Column('selection_set_version_id', sa.Integer(), nullable=True),
    sa.Column('feedback_set_version_id', sa.Integer(), nullable=True),
    sa.Column('assistance_policy', sa.String(length=40), nullable=False),
    sa.Column('reannotation_mode', sa.String(length=30), nullable=False),
    sa.Column('annotator_user_ids', JSONType(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('sequence > 0', name='ck_annotation_rounds_positive_sequence'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['cycle_id'], ['learning_cycles.id'], ),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_versions.id'], ),
    sa.ForeignKeyConstraint(['feedback_set_version_id'], ['feedback_set_versions.id'], ),
    sa.ForeignKeyConstraint(['guideline_revision_id'], ['guideline_revisions.id'], ),
    sa.ForeignKeyConstraint(['parent_round_id'], ['annotation_rounds.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['selection_set_version_id'], ['selection_set_versions.id'], ),
    sa.ForeignKeyConstraint(['task_version_id'], ['task_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'cycle_id', 'sequence', name='uq_annotation_rounds_cycle_sequence')
    )
    with op.batch_alter_table('annotation_rounds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_annotation_rounds_assistance_policy'), ['assistance_policy'], unique=False)
        batch_op.create_index(batch_op.f('ix_annotation_rounds_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_annotation_rounds_cycle_id'), ['cycle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_annotation_rounds_dataset_version_id'), ['dataset_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_annotation_rounds_feedback_set_version_id'), ['feedback_set_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_annotation_rounds_guideline_revision_id'), ['guideline_revision_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_annotation_rounds_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_annotation_rounds_parent_round_id'), ['parent_round_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_annotation_rounds_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_annotation_rounds_reannotation_mode'), ['reannotation_mode'], unique=False)
        batch_op.create_index(batch_op.f('ix_annotation_rounds_selection_set_version_id'), ['selection_set_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_annotation_rounds_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_annotation_rounds_task_version_id'), ['task_version_id'], unique=False)

    op.create_table('guideline_impact_evaluations',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('guideline_revision_id', sa.Integer(), nullable=False),
    sa.Column('pilot_round_id', sa.Integer(), nullable=False),
    sa.Column('protected_split_map_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('metrics', JSONType(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['guideline_revision_id'], ['guideline_revisions.id'], ),
    sa.ForeignKeyConstraint(['pilot_round_id'], ['annotation_rounds.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['protected_split_map_id'], ['split_maps.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guideline_impact_evaluations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guideline_impact_evaluations_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guideline_impact_evaluations_guideline_revision_id'), ['guideline_revision_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guideline_impact_evaluations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guideline_impact_evaluations_pilot_round_id'), ['pilot_round_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guideline_impact_evaluations_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guideline_impact_evaluations_protected_split_map_id'), ['protected_split_map_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guideline_impact_evaluations_reviewed_by_user_id'), ['reviewed_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guideline_impact_evaluations_status'), ['status'], unique=False)

    op.create_table('round_items',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('annotation_round_id', sa.Integer(), nullable=False),
    sa.Column('dataset_item_id', sa.Integer(), nullable=False),
    sa.Column('selection_rank', sa.Integer(), nullable=True),
    sa.Column('selection_score', sa.Float(), nullable=True),
    sa.Column('selection_probability', sa.Float(), nullable=True),
    sa.Column('selection_reason', JSONType(), nullable=False),
    sa.Column('metadata', JSONType(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['annotation_round_id'], ['annotation_rounds.id'], ),
    sa.ForeignKeyConstraint(['dataset_item_id'], ['dataset_items.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('annotation_round_id', 'dataset_item_id', name='uq_round_items_round_item')
    )
    with op.batch_alter_table('round_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_round_items_annotation_round_id'), ['annotation_round_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_round_items_dataset_item_id'), ['dataset_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_round_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_round_items_project_id'), ['project_id'], unique=False)

    op.create_table('round_submissions',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('annotation_round_id', sa.Integer(), nullable=False),
    sa.Column('annotator_user_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('decision_ids', JSONType(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint('sequence > 0', name='ck_round_submissions_positive_sequence'),
    sa.ForeignKeyConstraint(['annotation_round_id'], ['annotation_rounds.id'], ),
    sa.ForeignKeyConstraint(['annotator_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('annotation_round_id', 'annotator_user_id', 'sequence', name='uq_round_submissions_round_annotator_sequence')
    )
    with op.batch_alter_table('round_submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_round_submissions_annotation_round_id'), ['annotation_round_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_round_submissions_annotator_user_id'), ['annotator_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_round_submissions_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_round_submissions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_round_submissions_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_round_submissions_submitted_at'), ['submitted_at'], unique=False)

    op.create_table('feedback_events',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=True),
    sa.Column('annotation_round_id', sa.Integer(), nullable=True),
    sa.Column('round_item_id', sa.Integer(), nullable=True),
    sa.Column('feedback_candidate_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('payload', JSONType(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['annotation_round_id'], ['annotation_rounds.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['cycle_id'], ['learning_cycles.id'], ),
    sa.ForeignKeyConstraint(['feedback_candidate_id'], ['feedback_candidates.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['round_item_id'], ['round_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedback_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_events_annotation_round_id'), ['annotation_round_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_events_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_events_cycle_id'), ['cycle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_events_feedback_candidate_id'), ['feedback_candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_events_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_events_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_events_round_item_id'), ['round_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_events_severity'), ['severity'], unique=False)

    op.create_table('feedback_exposures',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('round_item_id', sa.Integer(), nullable=False),
    sa.Column('feedback_candidate_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exposure_mode', sa.String(length=40), nullable=False),
    sa.Column('context', JSONType(), nullable=False),
    sa.Column('exposed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['feedback_candidate_id'], ['feedback_candidates.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['round_item_id'], ['round_items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedback_exposures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_exposures_exposed_at'), ['exposed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_exposures_exposure_mode'), ['exposure_mode'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_exposures_feedback_candidate_id'), ['feedback_candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_exposures_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_exposures_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_exposures_round_item_id'), ['round_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_exposures_user_id'), ['user_id'], unique=False)

    op.create_table('round_annotation_decisions',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('round_item_id', sa.Integer(), nullable=False),
    sa.Column('annotator_user_id', sa.Integer(), nullable=False),
    sa.Column('supersedes_decision_id', sa.Integer(), nullable=True),
    sa.Column('output', JSONType(), nullable=False),
    sa.Column('decision_kind', sa.String(length=30), nullable=False),
    sa.Column('is_initial_checkpoint', sa.Boolean(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['annotator_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['round_item_id'], ['round_items.id'], ),
    sa.ForeignKeyConstraint(['supersedes_decision_id'], ['round_annotation_decisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('round_annotation_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_round_annotation_decisions_annotator_user_id'), ['annotator_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_round_annotation_decisions_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_round_annotation_decisions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_round_annotation_decisions_decision_kind'), ['decision_kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_round_annotation_decisions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_round_annotation_decisions_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_round_annotation_decisions_round_item_id'), ['round_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_round_annotation_decisions_supersedes_decision_id'), ['supersedes_decision_id'], unique=False)

    op.create_table('feedback_decisions',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('feedback_exposure_id', sa.Integer(), nullable=False),
    sa.Column('round_annotation_decision_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=30), nullable=False),
    sa.Column('details', JSONType(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['feedback_exposure_id'], ['feedback_exposures.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['round_annotation_decision_id'], ['round_annotation_decisions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedback_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_decisions_decided_at'), ['decided_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_decisions_decision'), ['decision'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_decisions_feedback_exposure_id'), ['feedback_exposure_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_decisions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_decisions_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_decisions_round_annotation_decision_id'), ['round_annotation_decision_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_decisions_user_id'), ['user_id'], unique=False)

    op.create_table('review_cases',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('feedback_event_id', sa.Integer(), nullable=False),
    sa.Column('assigned_to_user_id', sa.Integer(), nullable=True),
    sa.Column('case_type', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('resolution', JSONType(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['feedback_event_id'], ['feedback_events.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_cases_assigned_to_user_id'), ['assigned_to_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_cases_case_type'), ['case_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_cases_feedback_event_id'), ['feedback_event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_cases_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_cases_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_cases_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_cases_status'))
        batch_op.drop_index(batch_op.f('ix_review_cases_project_id'))
        batch_op.drop_index(batch_op.f('ix_review_cases_id'))
        batch_op.drop_index(batch_op.f('ix_review_cases_feedback_event_id'))
        batch_op.drop_index(batch_op.f('ix_review_cases_case_type'))
        batch_op.drop_index(batch_op.f('ix_review_cases_assigned_to_user_id'))

    op.drop_table('review_cases')
    with op.batch_alter_table('feedback_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_decisions_user_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_decisions_round_annotation_decision_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_decisions_project_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_decisions_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_decisions_feedback_exposure_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_decisions_decision'))
        batch_op.drop_index(batch_op.f('ix_feedback_decisions_decided_at'))

    op.drop_table('feedback_decisions')
    with op.batch_alter_table('round_annotation_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_round_annotation_decisions_supersedes_decision_id'))
        batch_op.drop_index(batch_op.f('ix_round_annotation_decisions_round_item_id'))
        batch_op.drop_index(batch_op.f('ix_round_annotation_decisions_project_id'))
        batch_op.drop_index(batch_op.f('ix_round_annotation_decisions_id'))
        batch_op.drop_index(batch_op.f('ix_round_annotation_decisions_decision_kind'))
        batch_op.drop_index(batch_op.f('ix_round_annotation_decisions_created_at'))
        batch_op.drop_index(batch_op.f('ix_round_annotation_decisions_content_hash'))
        batch_op.drop_index(batch_op.f('ix_round_annotation_decisions_annotator_user_id'))

    op.drop_table('round_annotation_decisions')
    with op.batch_alter_table('feedback_exposures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_exposures_user_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_exposures_round_item_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_exposures_project_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_exposures_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_exposures_feedback_candidate_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_exposures_exposure_mode'))
        batch_op.drop_index(batch_op.f('ix_feedback_exposures_exposed_at'))

    op.drop_table('feedback_exposures')
    with op.batch_alter_table('feedback_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_events_severity'))
        batch_op.drop_index(batch_op.f('ix_feedback_events_round_item_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_events_project_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_events_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_feedback_events_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_events_feedback_candidate_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_feedback_events_cycle_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_events_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_events_annotation_round_id'))

    op.drop_table('feedback_events')
    with op.batch_alter_table('round_submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_round_submissions_submitted_at'))
        batch_op.drop_index(batch_op.f('ix_round_submissions_project_id'))
        batch_op.drop_index(batch_op.f('ix_round_submissions_id'))
        batch_op.drop_index(batch_op.f('ix_round_submissions_content_hash'))
        batch_op.drop_index(batch_op.f('ix_round_submissions_annotator_user_id'))
        batch_op.drop_index(batch_op.f('ix_round_submissions_annotation_round_id'))

    op.drop_table('round_submissions')
    with op.batch_alter_table('round_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_round_items_project_id'))
        batch_op.drop_index(batch_op.f('ix_round_items_id'))
        batch_op.drop_index(batch_op.f('ix_round_items_dataset_item_id'))
        batch_op.drop_index(batch_op.f('ix_round_items_annotation_round_id'))

    op.drop_table('round_items')
    with op.batch_alter_table('guideline_impact_evaluations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guideline_impact_evaluations_status'))
        batch_op.drop_index(batch_op.f('ix_guideline_impact_evaluations_reviewed_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_guideline_impact_evaluations_protected_split_map_id'))
        batch_op.drop_index(batch_op.f('ix_guideline_impact_evaluations_project_id'))
        batch_op.drop_index(batch_op.f('ix_guideline_impact_evaluations_pilot_round_id'))
        batch_op.drop_index(batch_op.f('ix_guideline_impact_evaluations_id'))
        batch_op.drop_index(batch_op.f('ix_guideline_impact_evaluations_guideline_revision_id'))
        batch_op.drop_index(batch_op.f('ix_guideline_impact_evaluations_created_by_user_id'))

    op.drop_table('guideline_impact_evaluations')
    with op.batch_alter_table('annotation_rounds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_annotation_rounds_task_version_id'))
        batch_op.drop_index(batch_op.f('ix_annotation_rounds_status'))
        batch_op.drop_index(batch_op.f('ix_annotation_rounds_selection_set_version_id'))
        batch_op.drop_index(batch_op.f('ix_annotation_rounds_reannotation_mode'))
        batch_op.drop_index(batch_op.f('ix_annotation_rounds_project_id'))
        batch_op.drop_index(batch_op.f('ix_annotation_rounds_parent_round_id'))
        batch_op.drop_index(batch_op.f('ix_annotation_rounds_id'))
        batch_op.drop_index(batch_op.f('ix_annotation_rounds_guideline_revision_id'))
        batch_op.drop_index(batch_op.f('ix_annotation_rounds_feedback_set_version_id'))
        batch_op.drop_index(batch_op.f('ix_annotation_rounds_dataset_version_id'))
        batch_op.drop_index(batch_op.f('ix_annotation_rounds_cycle_id'))
        batch_op.drop_index(batch_op.f('ix_annotation_rounds_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_annotation_rounds_assistance_policy'))

    op.drop_table('annotation_rounds')
    with op.batch_alter_table('selection_set_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_selection_set_versions_selection_run_id'))
        batch_op.drop_index(batch_op.f('ix_selection_set_versions_project_id'))
        batch_op.drop_index(batch_op.f('ix_selection_set_versions_id'))
        batch_op.drop_index(batch_op.f('ix_selection_set_versions_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_selection_set_versions_content_hash'))

    op.drop_table('selection_set_versions')
    with op.batch_alter_table('selection_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_selection_runs_task_version_id'))
        batch_op.drop_index(batch_op.f('ix_selection_runs_strategy'))
        batch_op.drop_index(batch_op.f('ix_selection_runs_status'))
        batch_op.drop_index(batch_op.f('ix_selection_runs_split_map_id'))
        batch_op.drop_index(batch_op.f('ix_selection_runs_project_id'))
        batch_op.drop_index(batch_op.f('ix_selection_runs_id'))
        batch_op.drop_index(batch_op.f('ix_selection_runs_feedback_set_version_id'))
        batch_op.drop_index(batch_op.f('ix_selection_runs_dataset_version_id'))
        batch_op.drop_index(batch_op.f('ix_selection_runs_cycle_id'))
        batch_op.drop_index(batch_op.f('ix_selection_runs_created_by_user_id'))

    op.drop_table('selection_runs')
    with op.batch_alter_table('feedback_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_candidates_project_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_candidates_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_candidates_feedback_set_version_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_candidates_dataset_item_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_candidates_content_hash'))

    op.drop_table('feedback_candidates')
    with op.batch_alter_table('feedback_set_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_set_versions_task_version_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_set_versions_project_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_set_versions_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_set_versions_feedback_run_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_set_versions_dataset_version_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_set_versions_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_set_versions_content_hash'))
        batch_op.drop_index(batch_op.f('ix_feedback_set_versions_artifact_package_id'))

    op.drop_table('feedback_set_versions')
    with op.batch_alter_table('feedback_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_runs_task_version_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_runs_status'))
        batch_op.drop_index(batch_op.f('ix_feedback_runs_project_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_runs_producer_type'))
        batch_op.drop_index(batch_op.f('ix_feedback_runs_model_version_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_runs_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_runs_dataset_version_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_runs_cycle_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_runs_created_by_user_id'))

    op.drop_table('feedback_runs')
    with op.batch_alter_table('training_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_runs_training_dataset_version_id'))
        batch_op.drop_index(batch_op.f('ix_training_runs_task_version_id'))
        batch_op.drop_index(batch_op.f('ix_training_runs_storage_policy_id'))
        batch_op.drop_index(batch_op.f('ix_training_runs_status'))
        batch_op.drop_index(batch_op.f('ix_training_runs_registered_model_id'))
        batch_op.drop_index(batch_op.f('ix_training_runs_recipe_version_id'))
        batch_op.drop_index(batch_op.f('ix_training_runs_project_id'))
        batch_op.drop_index(batch_op.f('ix_training_runs_parent_model_version_id'))
        batch_op.drop_index(batch_op.f('ix_training_runs_output_model_version_id'))
        batch_op.drop_index(batch_op.f('ix_training_runs_launch_hash'))
        batch_op.drop_index(batch_op.f('ix_training_runs_id'))
        batch_op.drop_index(batch_op.f('ix_training_runs_environment_id'))
        batch_op.drop_index(batch_op.f('ix_training_runs_created_by_user_id'))

    op.drop_table('training_runs')
    with op.batch_alter_table('learning_cycles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_cycles_task_version_id'))
        batch_op.drop_index(batch_op.f('ix_learning_cycles_status'))
        batch_op.drop_index(batch_op.f('ix_learning_cycles_source_dataset_version_id'))
        batch_op.drop_index(batch_op.f('ix_learning_cycles_project_id'))
        batch_op.drop_index(batch_op.f('ix_learning_cycles_parent_cycle_id'))
        batch_op.drop_index(batch_op.f('ix_learning_cycles_output_training_dataset_version_id'))
        batch_op.drop_index(batch_op.f('ix_learning_cycles_output_model_version_id'))
        batch_op.drop_index(batch_op.f('ix_learning_cycles_id'))
        batch_op.drop_index(batch_op.f('ix_learning_cycles_goal'))
        batch_op.drop_index(batch_op.f('ix_learning_cycles_current_stage'))
        batch_op.drop_index(batch_op.f('ix_learning_cycles_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_learning_cycles_baseline_model_version_id'))

    op.drop_table('learning_cycles')
    with op.batch_alter_table('model_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_versions_training_method'))
        batch_op.drop_index(batch_op.f('ix_model_versions_training_dataset_version_id'))
        batch_op.drop_index(batch_op.f('ix_model_versions_task_version_id'))
        batch_op.drop_index(batch_op.f('ix_model_versions_registered_model_id'))
        batch_op.drop_index(batch_op.f('ix_model_versions_project_id'))
        batch_op.drop_index(batch_op.f('ix_model_versions_parent_version_id'))
        batch_op.drop_index(batch_op.f('ix_model_versions_legacy_training_experiment_id'))
        batch_op.drop_index(batch_op.f('ix_model_versions_id'))
        batch_op.drop_index(batch_op.f('ix_model_versions_framework'))
        batch_op.drop_index(batch_op.f('ix_model_versions_family'))
        batch_op.drop_index(batch_op.f('ix_model_versions_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_model_versions_content_hash'))
        batch_op.drop_index(batch_op.f('ix_model_versions_checkpoint_package_id'))

    op.drop_table('model_versions')
    with op.batch_alter_table('training_dataset_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_dataset_versions_task_version_id'))
        batch_op.drop_index(batch_op.f('ix_training_dataset_versions_split_map_id'))
        batch_op.drop_index(batch_op.f('ix_training_dataset_versions_project_id'))
        batch_op.drop_index(batch_op.f('ix_training_dataset_versions_id'))
        batch_op.drop_index(batch_op.f('ix_training_dataset_versions_dataset_version_id'))
        batch_op.drop_index(batch_op.f('ix_training_dataset_versions_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_training_dataset_versions_content_hash'))
        batch_op.drop_index(batch_op.f('ix_training_dataset_versions_artifact_package_id'))

    op.drop_table('training_dataset_versions')
    with op.batch_alter_table('split_maps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_split_maps_project_id'))
        batch_op.drop_index(batch_op.f('ix_split_maps_id'))
        batch_op.drop_index(batch_op.f('ix_split_maps_dataset_version_id'))
        batch_op.drop_index(batch_op.f('ix_split_maps_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_split_maps_content_hash'))

    op.drop_table('split_maps')
    with op.batch_alter_table('label_set_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_label_set_versions_task_version_id'))
        batch_op.drop_index(batch_op.f('ix_label_set_versions_source_kind'))
        batch_op.drop_index(batch_op.f('ix_label_set_versions_project_id'))
        batch_op.drop_index(batch_op.f('ix_label_set_versions_parent_version_id'))
        batch_op.drop_index(batch_op.f('ix_label_set_versions_id'))
        batch_op.drop_index(batch_op.f('ix_label_set_versions_dataset_version_id'))
        batch_op.drop_index(batch_op.f('ix_label_set_versions_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_label_set_versions_content_hash'))
        batch_op.drop_index(batch_op.f('ix_label_set_versions_artifact_package_id'))

    op.drop_table('label_set_versions')
    with op.batch_alter_table('guideline_change_proposals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guideline_change_proposals_status'))
        batch_op.drop_index(batch_op.f('ix_guideline_change_proposals_reviewed_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_guideline_change_proposals_resulting_revision_id'))
        batch_op.drop_index(batch_op.f('ix_guideline_change_proposals_project_id'))
        batch_op.drop_index(batch_op.f('ix_guideline_change_proposals_id'))
        batch_op.drop_index(batch_op.f('ix_guideline_change_proposals_guideline_id'))
        batch_op.drop_index(batch_op.f('ix_guideline_change_proposals_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_guideline_change_proposals_base_revision_id'))

    op.drop_table('guideline_change_proposals')
    with op.batch_alter_table('dataset_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dataset_items_project_id'))
        batch_op.drop_index(batch_op.f('ix_dataset_items_id'))
        batch_op.drop_index(batch_op.f('ix_dataset_items_group_key'))
        batch_op.drop_index(batch_op.f('ix_dataset_items_dataset_version_id'))
        batch_op.drop_index(batch_op.f('ix_dataset_items_content_hash'))

    op.drop_table('dataset_items')
    with op.batch_alter_table('guideline_revisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guideline_revisions_task_version_id'))
        batch_op.drop_index(batch_op.f('ix_guideline_revisions_status'))
        batch_op.drop_index(batch_op.f('ix_guideline_revisions_project_id'))
        batch_op.drop_index(batch_op.f('ix_guideline_revisions_parent_revision_id'))
        batch_op.drop_index(batch_op.f('ix_guideline_revisions_id'))
        batch_op.drop_index(batch_op.f('ix_guideline_revisions_guideline_id'))
        batch_op.drop_index(batch_op.f('ix_guideline_revisions_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_guideline_revisions_content_hash'))
        batch_op.drop_index(batch_op.f('ix_guideline_revisions_approved_by_user_id'))

    op.drop_table('guideline_revisions')
    with op.batch_alter_table('dataset_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dataset_versions_project_id'))
        batch_op.drop_index(batch_op.f('ix_dataset_versions_id'))
        batch_op.drop_index(batch_op.f('ix_dataset_versions_dataset_id'))
        batch_op.drop_index(batch_op.f('ix_dataset_versions_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_dataset_versions_content_hash'))
        batch_op.drop_index(batch_op.f('ix_dataset_versions_artifact_package_id'))

    op.drop_table('dataset_versions')
    with op.batch_alter_table('training_recipe_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_recipe_versions_training_recipe_id'))
        batch_op.drop_index(batch_op.f('ix_training_recipe_versions_trainer_plugin_key'))
        batch_op.drop_index(batch_op.f('ix_training_recipe_versions_project_id'))
        batch_op.drop_index(batch_op.f('ix_training_recipe_versions_id'))
        batch_op.drop_index(batch_op.f('ix_training_recipe_versions_environment_class'))
        batch_op.drop_index(batch_op.f('ix_training_recipe_versions_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_training_recipe_versions_content_hash'))

    op.drop_table('training_recipe_versions')
    with op.batch_alter_table('task_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_versions_task_kind'))
        batch_op.drop_index(batch_op.f('ix_task_versions_task_definition_id'))
        batch_op.drop_index(batch_op.f('ix_task_versions_project_id'))
        batch_op.drop_index(batch_op.f('ix_task_versions_id'))
        batch_op.drop_index(batch_op.f('ix_task_versions_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_task_versions_content_hash'))

    op.drop_table('task_versions')
    with op.batch_alter_table('guidelines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guidelines_task_definition_id'))
        batch_op.drop_index(batch_op.f('ix_guidelines_project_id'))
        batch_op.drop_index(batch_op.f('ix_guidelines_id'))
        batch_op.drop_index(batch_op.f('ix_guidelines_created_by_user_id'))

    op.drop_table('guidelines')
    with op.batch_alter_table('training_recipes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_recipes_project_id'))
        batch_op.drop_index(batch_op.f('ix_training_recipes_id'))
        batch_op.drop_index(batch_op.f('ix_training_recipes_created_by_user_id'))

    op.drop_table('training_recipes')
    with op.batch_alter_table('task_definitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_definitions_project_id'))
        batch_op.drop_index(batch_op.f('ix_task_definitions_id'))
        batch_op.drop_index(batch_op.f('ix_task_definitions_created_by_user_id'))

    op.drop_table('task_definitions')
    with op.batch_alter_table('storage_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_storage_policies_project_id'))
        batch_op.drop_index(batch_op.f('ix_storage_policies_is_default'))
        batch_op.drop_index(batch_op.f('ix_storage_policies_id'))
        batch_op.drop_index(batch_op.f('ix_storage_policies_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_storage_policies_backend'))

    op.drop_table('storage_policies')
    with op.batch_alter_table('registered_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registered_models_project_id'))
        batch_op.drop_index(batch_op.f('ix_registered_models_lifecycle_status'))
        batch_op.drop_index(batch_op.f('ix_registered_models_id'))
        batch_op.drop_index(batch_op.f('ix_registered_models_created_by_user_id'))

    op.drop_table('registered_models')
    with op.batch_alter_table('execution_environments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_execution_environments_status'))
        batch_op.drop_index(batch_op.f('ix_execution_environments_project_id'))
        batch_op.drop_index(batch_op.f('ix_execution_environments_id'))
        batch_op.drop_index(batch_op.f('ix_execution_environments_environment_class'))
        batch_op.drop_index(batch_op.f('ix_execution_environments_created_by_user_id'))

    op.drop_table('execution_environments')
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_datasets_source_type'))
        batch_op.drop_index(batch_op.f('ix_datasets_project_id'))
        batch_op.drop_index(batch_op.f('ix_datasets_id'))
        batch_op.drop_index(batch_op.f('ix_datasets_created_by_user_id'))

    op.drop_table('datasets')
    # ### end Alembic commands ###
